# Generated by Django 3.0.4 on 2020-03-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo', models.CharField(default='foo', max_length=255)),
                ('bar', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo', models.CharField(default='foo', max_length=255)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='DoubleRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.CharField(default='bar', max_length=255)),
                ('samples', models.ManyToManyField(blank=True, to='app.Sample')),
            ],
        ),
    ]
